version: "3"
services:
  "tlstransfer-client.example.com":
    image: tlstransfer
    hostname: tlstransfer-client
    domainname: tlstransfer-client.example.com
    command: ["client", "copy", "tlstransfer-server.example.com", "33333", "-o output_file.md", "README.md"]
    depends_on:
      - tlstransfer-server.example.com
    environment:
      JAVA_OPTS: -Djava.util.logging.level=FINEST  -Djavax.net.ssl.trustStore=certificates/tlstransfer-server.example.com/KeyStore.jks -Djavax.net.ssl.trustStorePassword=tester1234
  "tlstransfer-server.example.com":
    image: tlstransfer
    command: ["server", "--key-store=certificates/tlstransfer-server.example.com/KeyStore.jks", "--key-store-password=tester1234", "33333", "/tmp/src"]
    hostname: tlstransfer-server
    domainname: tlstransfer-server.example.com
    environment:
      JAVA_OPTS: -Djava.util.logging.ConsoleHandler.level=FINEST  -Djavax.net.ssl.trustStore=certificates/tlstransfer-server.example.com/KeyStore.jks -Djavax.net.ssl.trustStorePassword=tester1234
#      JAVA_OPTS: -Djavax.net.debug=all
    ports:
      - "33333"
