# Build and Test the TLSTransfer Server
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Tests on Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Build Code
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Upload Build Artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/tlstransfer.jar

  test:
    name: Run Tests on Build Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      # Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target/  
      
      - name: Run Python Tests
        run: |
          ls .
          ls ./target
          find .


      # Setup Java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3
          architecture: x64
      
      # Install Test Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./test/requirements.txt
          
      # Runs Tests
      - name: Run Python Tests
        run: pytest ./test/main.py
